packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
  - "standalone-panels/*"
  - "backend"
  - "."

allowBuilds:
  "@firebase/util": true
  "@nestjs/core": true
  protobufjs: true
  sharp: true
  vue-demi: true
