import { TemplateDefinition } from "./types";

export const DEFAULT_COMPANY = {
  companyName: "NovaTech Cloud Systems Pvt. Ltd.",
  companyTagline: "Next-Generation Enterprise SaaS & Cloud Intelligence",
  companyAddress: "Building 4B, Mindspace IT Park, Hitech City",
  companyCityState: "Hyderabad, Telangana 500081",
  companyEmail: "billing@novatechcloud.com",
  companyPhone: "+91 98765 43210",
  companyGstin: "36AABCN1234F1Z5",
  companyPan: "AABCN1234F",
};

export const DEFAULT_CUSTOMER = {
  customerName: "Aarav Sharma",
  customerCompany: "Apex Digital Solutions Pvt. Ltd.",
  customerAddress: "Suite 302, Cyber Towers, Madhapur",
  customerCityState: "Hyderabad, Telangana 500081",
  customerEmail: "finance@apexdigital.io",
  customerPhone: "+91 91234 56789",
  customerGstin: "36AAACA9876K1Z2",
};

export const TEMPLATES_REGISTRY: TemplateDefinition[] = [
  {
    id: "saas-invoice",
    name: "Vertofi SaaS Invoice",
    slug: "saas-invoice",
    category: "Invoices",
    description: "Modern, high-converting invoice template tailored for SaaS subscriptions, cloud usage, and user seat billing.",
    tier: "Free",
    popularity: 98,
    isNew: true,
    paperSize: "A4",
    features: [
      "Subscription Seat Billing",
      "GSTIN & HSN Breakdowns",
      "Dynamic UPI QR Code",
      "Automated Rupee Words Conversion",
      "Bank Account Wire Details",
      "Print & PDF Optimized",
    ],
    defaultFormData: {
      primaryColor: "#0B132B",
      secondaryColor: "#1E60D5",
      themePreset: "Vertofi Modern",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      ...DEFAULT_CUSTOMER,
      docNumber: "INV-2026-0891",
      docDate: "2026-09-01",
      dueDate: "2026-09-15",
      placeOfSupply: "36-TELANGANA",
      billingPeriod: "01 Sep 2026 - 30 Sep 2026",
      subscriptionPlan: "Enterprise Scale Plan (Annual Commitment)",
      numberOfUsers: 45,
      items: [
        {
          id: "1",
          name: "Vertofi Platform Enterprise User Seats",
          description: "45 Active Team User Licenses (@ ₹800/seat/mo)",
          hsnSac: "998313",
          quantity: 45,
          rate: 800,
          discountPct: 5,
          taxPct: 18,
          total: 34200,
        },
        {
          id: "2",
          name: "Dedicated AI Agent Processing Tokens",
          description: "Monthly compute quota add-on for automated workflows",
          hsnSac: "998314",
          quantity: 1,
          rate: 12000,
          discountPct: 0,
          taxPct: 18,
          total: 12000,
        },
        {
          id: "3",
          name: "24/7 Priority SLA SLA Support Package",
          description: "Dedicated Technical Account Manager & 15-min SLA",
          hsnSac: "998315",
          quantity: 1,
          rate: 5000,
          discountPct: 0,
          taxPct: 18,
          total: 5000,
        },
      ],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      paymentMethod: "Bank Transfer (NEFT/RTGS/UPI)",
      transactionId: "TXN-9988221100",
      paymentStatus: "UNPAID",
      bankName: "HDFC Bank Ltd.",
      bankAccountNo: "50200088991122",
      bankIfsc: "HDFC0000240",
      bankBranch: "Hitech City Branch, Hyderabad",
      upiId: "novatech@hdfcbank",
      showUpiQr: true,
      termsAndConditions:
        "1. Payments are due within 15 days of invoice date.\n2. Overdue payments incur interest at 18% p.a.\n3. Goods & Services tax billed as per GST Act 2017.",
      notes: "Thank you for choosing Vertofi Platform for your digital cloud transformation!",
      signatoryTitle: "Authorized Signatory - Accounts & Finance",
    },
  },
  {
    id: "service-invoice",
    name: "Vertofi Service Invoice",
    slug: "service-invoice",
    category: "Invoices",
    description: "Clean invoice layout designed for software development, IT consulting, agency projects, and cloud services.",
    tier: "Free",
    popularity: 92,
    paperSize: "A4",
    features: [
      "Milestone & Hourly Support",
      "GST HSN Code Support",
      "Brand Color Customization",
      "UPI Scan & Pay",
      "Digital Stamp Space",
    ],
    defaultFormData: {
      primaryColor: "#059669",
      secondaryColor: "#10B981",
      themePreset: "Vertofi Professional",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      ...DEFAULT_CUSTOMER,
      docNumber: "SRV-2026-0421",
      docDate: "2026-09-02",
      dueDate: "2026-09-16",
      placeOfSupply: "36-TELANGANA",
      projectName: "Custom Microservices Architecture Implementation",
      items: [
        {
          id: "1",
          name: "Backend Architecture & API Engineering",
          description: "Sprint 1 & Sprint 2 Microservice Node.js Development",
          hsnSac: "998313",
          quantity: 80,
          rate: 1500,
          discountPct: 0,
          taxPct: 18,
          total: 120000,
        },
        {
          id: "2",
          name: "DevOps & Kubernetes Cloud Deployment",
          description: "AWS EKS cluster setup, CI/CD pipeline & security hardening",
          hsnSac: "998315",
          quantity: 1,
          rate: 35000,
          discountPct: 10,
          taxPct: 18,
          total: 31500,
        },
      ],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      paymentMethod: "UPI / Bank Transfer",
      paymentStatus: "UNPAID",
      bankName: "ICICI Bank Ltd.",
      bankAccountNo: "00040500112233",
      bankIfsc: "ICIC0000004",
      bankBranch: "Madhapur Branch, Hyderabad",
      upiId: "novatechservices@icici",
      showUpiQr: true,
      termsAndConditions:
        "1. All deliverables subject to acceptance testing within 7 business days.\n2. Source code IP rights transferred upon receipt of full payment.",
      notes: "We appreciate your partnership on this cloud transformation project.",
      signatoryTitle: "Authorized Signatory",
    },
  },
  {
    id: "subscription-invoice",
    name: "Vertofi Subscription Invoice",
    slug: "subscription-invoice",
    category: "Subscriptions",
    description: "Automated recurring billing invoice with cycle dates, plan details, user counts, and next renewal date.",
    tier: "Premium",
    popularity: 88,
    isNew: true,
    paperSize: "A4",
    features: [
      "Subscription Cycle Tracker",
      "Next Auto-Renewal Date",
      "User Tier Breakdown",
      "Instant PDF Generation",
    ],
    defaultFormData: {
      primaryColor: "#4F46E5",
      secondaryColor: "#6366F1",
      themePreset: "Vertofi Modern",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      ...DEFAULT_CUSTOMER,
      docNumber: "SUB-2026-9042",
      docDate: "2026-09-01",
      dueDate: "2026-09-05",
      placeOfSupply: "36-TELANGANA",
      billingPeriod: "01 Sep 2026 - 01 Oct 2026",
      subscriptionPlan: "Vertofi Growth SaaS - Monthly Recurring",
      numberOfUsers: 25,
      items: [
        {
          id: "1",
          name: "Vertofi Growth Subscription (25 Seats)",
          description: "Monthly subscription period: Sep 1 to Oct 1, 2026",
          hsnSac: "998313",
          quantity: 25,
          rate: 600,
          discountPct: 0,
          taxPct: 18,
          total: 15000,
        },
        {
          id: "2",
          name: "WhatsApp Business API Connectivity Add-on",
          description: "5,000 Included Monthly Transactional Notifications",
          hsnSac: "998413",
          quantity: 1,
          rate: 3500,
          discountPct: 0,
          taxPct: 18,
          total: 3500,
        },
      ],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      paymentMethod: "Auto Debit (Razorpay Recurring)",
      transactionId: "PAY-SUB-77112233",
      paymentStatus: "PAID",
      bankName: "HDFC Bank Ltd.",
      bankAccountNo: "50200088991122",
      bankIfsc: "HDFC0000240",
      bankBranch: "Hitech City",
      upiId: "novatech@hdfcbank",
      showUpiQr: false,
      termsAndConditions: "Recurring subscription auto-renews on Oct 1, 2026 unless cancelled 48 hours prior.",
      notes: "Payment successfully received via Auto-Debit.",
      signatoryTitle: "Billing Operations Team",
    },
  },
  {
    id: "business-quotation",
    name: "Vertofi Business Quotation",
    slug: "business-quotation",
    category: "Quotations",
    description: "Professional cost estimate & proposal quotation document with validity date, milestone breakdown, and acceptance block.",
    tier: "Free",
    popularity: 95,
    paperSize: "A4",
    features: [
      "Validity Expiry Date",
      "Milestone Pricing Breakdown",
      "Client Signature Acceptance Box",
      "Custom Scope Terms",
    ],
    defaultFormData: {
      primaryColor: "#0F172A",
      secondaryColor: "#2563EB",
      themePreset: "Vertofi Corporate",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      ...DEFAULT_CUSTOMER,
      docNumber: "QUO-2026-0312",
      docDate: "2026-09-05",
      validUntilDate: "2026-09-25",
      preparedBy: "Vikram Malhotra (Lead Cloud Consultant)",
      projectName: "Enterprise ERP & Inventory Platform Migration",
      projectDescription: "Migration of legacy desktop accounting software to Vertofi Multi-tenant Cloud Platform.",
      items: [
        {
          id: "1",
          name: "Phase 1: Database Migration & Schema Mapping",
          description: "ETL scripts for 100,000+ ledger entries & inventory items",
          hsnSac: "998313",
          quantity: 1,
          rate: 45000,
          discountPct: 5,
          taxPct: 18,
          total: 42750,
        },
        {
          id: "2",
          name: "Phase 2: Custom Dashboard & GST e-Invoice Module",
          description: "Integration with NIC e-Invoice & e-Way Bill GSP APIs",
          hsnSac: "998313",
          quantity: 1,
          rate: 65000,
          discountPct: 5,
          taxPct: 18,
          total: 61750,
        },
        {
          id: "3",
          name: "Phase 3: Staff Training & User Onboarding",
          description: "Interactive remote training workshops for 20 team members",
          hsnSac: "998314",
          quantity: 1,
          rate: 15000,
          discountPct: 0,
          taxPct: 18,
          total: 15000,
        },
      ],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      paymentMethod: "50% Advance, 50% Upon Final Milestone Acceptance",
      paymentStatus: "PENDING",
      bankName: "HDFC Bank Ltd.",
      bankAccountNo: "50200088991122",
      bankIfsc: "HDFC0000240",
      bankBranch: "Hitech City",
      showUpiQr: false,
      termsAndConditions:
        "1. This quotation is valid for 20 days from date of issue.\n2. Milestone delivery timeline: 4 weeks from receiving 50% advance deposit.\n3. Taxes billed at actuals as per government regulations.",
      notes: "We look forward to partnering with your team on this digital transformation journey.",
      signatoryTitle: "Director - Cloud Services",
    },
  },
  {
    id: "project-proposal",
    name: "Vertofi Project Proposal",
    slug: "project-proposal",
    category: "Quotations",
    description: "Comprehensive proposal document suitable for enterprise pitches, software deliverables, executive summaries, and approvals.",
    tier: "Premium",
    popularity: 84,
    paperSize: "A4",
    features: [
      "Executive Summary Block",
      "Deliverable Schedule Table",
      "Approval & Acceptance Signatures",
      "SaaS Visual Styling",
    ],
    defaultFormData: {
      primaryColor: "#1E3A8A",
      secondaryColor: "#3B82F6",
      themePreset: "Vertofi Elegant",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      ...DEFAULT_CUSTOMER,
      docNumber: "PRP-2026-0045",
      docDate: "2026-09-04",
      validUntilDate: "2026-09-30",
      preparedBy: "Ananya Roy (Head of Solutions)",
      projectName: "AI-Powered Financial Analytics Engine",
      projectDescription: "Implementation of real-time cashflow forecasting and anomaly detection algorithms.",
      items: [
        {
          id: "1",
          name: "Solution Design & Architecture Specification",
          description: "Data modeling, security review, and API architecture blueprint",
          hsnSac: "998313",
          quantity: 1,
          rate: 50000,
          discountPct: 0,
          taxPct: 18,
          total: 50000,
        },
        {
          id: "2",
          name: "ML Model Training & Integration",
          description: "Custom cashflow forecasting model with 95%+ historical accuracy",
          hsnSac: "998314",
          quantity: 1,
          rate: 90000,
          discountPct: 10,
          taxPct: 18,
          total: 81000,
        },
      ],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      paymentMethod: "3 Stage Milestone Payments (30-40-30)",
      paymentStatus: "PENDING",
      termsAndConditions: "Proposal terms valid for 30 calendar days. Work commences upon signing.",
      notes: "Proposal includes 60 days post-launch hypercare support.",
      signatoryTitle: "Chief Technology Officer",
    },
  },
  {
    id: "payment-receipt",
    name: "Vertofi Payment Receipt",
    slug: "payment-receipt",
    category: "Receipts",
    description: "Official payment proof receipt featuring a bold 'PAID' stamp, transaction reference ID, and amount words.",
    tier: "Free",
    popularity: 96,
    paperSize: "A4",
    features: [
      "Prominent 'PAID' Badge Stamp",
      "Transaction ID Reference",
      "Rupee Amount Conversion",
      "UPI & Bank Confirmation",
    ],
    defaultFormData: {
      primaryColor: "#047857",
      secondaryColor: "#10B981",
      themePreset: "Vertofi Minimal",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      ...DEFAULT_CUSTOMER,
      docNumber: "RCT-2026-7781",
      docDate: "2026-09-06",
      dueDate: "2026-09-06",
      paymentMethod: "UPI Fast Transfer (GPay / PhonePe)",
      transactionId: "UPI/20260906/98711223344",
      paymentStatus: "PAID",
      items: [
        {
          id: "1",
          name: "Full Payment for Invoice #INV-2026-0891",
          description: "Enterprise SaaS Annual Subscription Fee",
          hsnSac: "998313",
          quantity: 1,
          rate: 51200,
          discountPct: 0,
          taxPct: 0,
          total: 51200,
        },
      ],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      bankName: "HDFC Bank Ltd.",
      upiId: "novatech@hdfcbank",
      showUpiQr: false,
      termsAndConditions: "This is a computer-generated electronic payment receipt. No physical signature required.",
      notes: "Payment received in full with thanks.",
      signatoryTitle: "Accounts Receivable Lead",
    },
  },
  {
    id: "proforma-invoice",
    name: "Vertofi Proforma Invoice",
    slug: "proforma-invoice",
    category: "Billing",
    description: "Preliminary invoice issued to customers prior to delivery of goods or services for advance billing approval.",
    tier: "Free",
    popularity: 90,
    paperSize: "A4",
    features: [
      "Advance Payment Instructions",
      "Estimated Delivery Timelines",
      "Full Tax Calculation",
      "Convertible to Final Invoice",
    ],
    defaultFormData: {
      primaryColor: "#D97706",
      secondaryColor: "#F59E0B",
      themePreset: "Vertofi Corporate",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      ...DEFAULT_CUSTOMER,
      docNumber: "PI-2026-0155",
      docDate: "2026-09-03",
      validUntilDate: "2026-09-18",
      placeOfSupply: "36-TELANGANA",
      items: [
        {
          id: "1",
          name: "Hardware Gateway Appliance - Vertofi IoT Edge",
          description: "Dual-core ARM Cortex, 4GB RAM, LTE Module (Advance Supply)",
          hsnSac: "847130",
          quantity: 5,
          rate: 18000,
          discountPct: 5,
          taxPct: 18,
          total: 85500,
        },
        {
          id: "2",
          name: "Freight & Insured Logistics Packaging",
          description: "Doorstep delivery to Hyderabad facility",
          hsnSac: "996511",
          quantity: 1,
          rate: 2500,
          discountPct: 0,
          taxPct: 18,
          total: 2500,
        },
      ],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      paymentMethod: "Bank Transfer prior to dispatch",
      paymentStatus: "UNPAID",
      bankName: "HDFC Bank Ltd.",
      bankAccountNo: "50200088991122",
      bankIfsc: "HDFC0000240",
      bankBranch: "Hitech City",
      upiId: "novatech@hdfcbank",
      showUpiQr: true,
      termsAndConditions: "Proforma Invoice for customer reference only. Dispatch initiated upon payment credit.",
      notes: "Estimated shipment dispatch: 3 business days from payment receipt.",
      signatoryTitle: "Supply Chain Manager",
    },
  },
  {
    id: "client-statement",
    name: "Vertofi Client Statement",
    slug: "client-statement",
    category: "Finance",
    description: "Periodic ledger account statement showing opening balance, invoice debits, payment credits, and net closing balance.",
    tier: "Premium",
    popularity: 87,
    paperSize: "A4",
    features: [
      "Ledger Debit & Credit Tracking",
      "Opening & Closing Balance Summary",
      "Overdue Balance Highlights",
      "Print Ready A4 Report",
    ],
    defaultFormData: {
      primaryColor: "#334155",
      secondaryColor: "#475569",
      themePreset: "Vertofi Professional",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      ...DEFAULT_CUSTOMER,
      docNumber: "STMT-2026-Q3",
      docDate: "2026-09-05",
      statementPeriod: "01 Jul 2026 - 31 Aug 2026",
      openingBalance: 15000,
      statementEntries: [
        {
          id: "e1",
          date: "2026-07-05",
          invoiceNo: "INV-2026-0611",
          description: "July Cloud SaaS Subscription",
          debit: 35400,
          credit: 0,
          balance: 50400,
        },
        {
          id: "e2",
          date: "2026-07-15",
          invoiceNo: "RCT-2026-4410",
          description: "Payment Received (UPI Fast)",
          debit: 0,
          credit: 50400,
          balance: 0,
        },
        {
          id: "e3",
          date: "2026-08-01",
          invoiceNo: "INV-2026-0750",
          description: "August Cloud SaaS + Add-on",
          debit: 41300,
          credit: 0,
          balance: 41300,
        },
      ],
      items: [
        {
          id: "1",
          name: "Closing Net Outstanding Balance",
          description: "Statement Balance as of Aug 31, 2026",
          quantity: 1,
          rate: 41300,
          discountPct: 0,
          taxPct: 0,
          total: 41300,
        },
      ],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      paymentMethod: "NEFT / RTGS / UPI",
      paymentStatus: "UNPAID",
      bankName: "HDFC Bank Ltd.",
      bankAccountNo: "50200088991122",
      bankIfsc: "HDFC0000240",
      bankBranch: "Hitech City",
      termsAndConditions: "Please verify all ledger entries. Report any discrepancy within 7 days.",
      notes: "Thank you for maintaining a clean payment history with NovaTech Cloud.",
      signatoryTitle: "Senior Accounts Officer",
    },
  },
  {
    id: "employee-payslip",
    name: "Vertofi Employee Payslip",
    slug: "employee-payslip",
    category: "HR",
    description: "Detailed salary payslip with earnings breakdown (Basic, HRA, Allowances), statutory deductions (PF, Tax), and net payout.",
    tier: "Free",
    popularity: 94,
    paperSize: "A4",
    features: [
      "Earnings & Deductions Grid",
      "Attendance & Leave Summary",
      "Employee ID & Department Info",
      "Confidential HR Design",
    ],
    defaultFormData: {
      primaryColor: "#0F172A",
      secondaryColor: "#2563EB",
      themePreset: "Vertofi Modern",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      customerName: "Kavya Reddy",
      customerCompany: "NovaTech Cloud Systems Pvt. Ltd.",
      customerAddress: "Flat 402, Cyber Heights, Gachibowli",
      customerCityState: "Hyderabad, Telangana 500032",
      customerEmail: "kavya.reddy@novatechcloud.com",
      customerPhone: "+91 98112 23344",
      customerGstin: "NA (Employee)",
      docNumber: "PAY-2026-08",
      docDate: "2026-08-31",
      employeeName: "Kavya Reddy",
      employeeId: "NVT-1048",
      department: "Engineering & Product",
      designation: "Senior Full Stack Engineer",
      joiningDate: "15 Jan 2024",
      payPeriod: "August 2026",
      workingDays: 22,
      presentDays: 21,
      leaveDays: 1,
      paidDays: 22,
      earnings: [
        { id: "e1", label: "Basic Salary", amount: 45000 },
        { id: "e2", label: "House Rent Allowance (HRA)", amount: 22500 },
        { id: "e3", label: "Special Allowance", amount: 18500 },
        { id: "e4", label: "Performance Incentive", amount: 9000 },
      ],
      deductions: [
        { id: "d1", label: "Provident Fund (PF)", amount: 1800 },
        { id: "d2", label: "Professional Tax (PT)", amount: 200 },
        { id: "d3", label: "Income Tax (TDS)", amount: 4500 },
      ],
      items: [
        {
          id: "1",
          name: "Net Take-Home Salary Payout",
          description: "Salary credited for August 2026 (Gross ₹95,000 - Deductions ₹6,500)",
          quantity: 1,
          rate: 88500,
          discountPct: 0,
          taxPct: 0,
          total: 88500,
        },
      ],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      paymentMethod: "Direct Bank Transfer (HDFC Salary Account)",
      paymentStatus: "PAID",
      bankName: "HDFC Bank Ltd.",
      bankAccountNo: "XXXX-XXXX-9988",
      termsAndConditions: "This document is private and confidential intended strictly for the employee.",
      notes: "Salary deposited into account ending in 9988 on Aug 31, 2026.",
      signatoryTitle: "Head of People & HR Operations",
    },
  },
  {
    id: "employment-certificate",
    name: "Vertofi Employment Certificate",
    slug: "employment-certificate",
    category: "HR",
    description: "Official employment background & experience verification certificate printed on company letterhead with seal block.",
    tier: "Free",
    popularity: 86,
    paperSize: "A4",
    features: [
      "Official Letterhead Layout",
      "Tenure & Performance Verification",
      "HR Seal & Signatory Space",
      "Print Ready A4 Format",
    ],
    defaultFormData: {
      primaryColor: "#1E293B",
      secondaryColor: "#475569",
      themePreset: "Vertofi Corporate",
      logoUrl: "",
      ...DEFAULT_COMPANY,
      customerName: "Rohan Verma",
      customerCompany: "Ex-Employee",
      customerAddress: "Road No. 12, Jubilee Hills",
      customerCityState: "Hyderabad, Telangana 500033",
      customerEmail: "rohan.verma@gmail.com",
      customerPhone: "+91 97788 99001",
      customerGstin: "NA",
      docNumber: "EXP-2026-019",
      docDate: "2026-08-31",
      employeeName: "Rohan Verma",
      employeeId: "NVT-0892",
      department: "DevOps & Cloud Security",
      designation: "Lead DevOps Specialist",
      joiningDate: "01 Feb 2023",
      lastWorkingDate: "31 Aug 2026",
      issueDate: "2026-08-31",
      items: [],
      discountOverallPct: 0,
      shippingCharges: 0,
      extraCharges: 0,
      paymentMethod: "N/A",
      paymentStatus: "PAID",
      termsAndConditions:
        "This certificate is issued upon employee request for career progression purposes. We wish Rohan all success in future endeavors.",
      notes: "During his tenure, Rohan demonstrated outstanding dedication and technical excellence.",
      signatoryTitle: "Vice President - Human Resources",
    },
  },
];
