{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vertofi.name" . }}
  labels: {{- include "vertofi.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels: {{- include "vertofi.selectorLabels" . | nindent 6 }}
{{- end }}
