apiVersion: v1
kind: Service
metadata:
  name: {{ include "vertofi.name" . }}
  labels: {{- include "vertofi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "vertofi.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
